### PR TITLE
Fix windows compilation

### PR DESCRIPTION
**Pull request by borancar**
- Fix the makefiles for Windows
- Specify target architecture, this fixes loading on latest SiFive provided gdb

### CODE REVIEW

**Comment by cgarlati** [comment]
Why are we using the "latest SiFive provided gdb" rather than the one
included in Hex Five's reference toolchain build?

Cesare Garlati | Hex Five Security, Inc. | www.hex-five.com | Ph 408 667
3320

/*Hex Five Security, Inc.* is the creator of MultiZone™ Security, the
first trusted execution environment for RISC-V. Hex Five patent pending
technology provides policy-based hardware-enforced separation for an
unlimited number of security domains, with full control over data, code
and peripherals. Contrary to traditional solutions, Hex Five MultiZone™
requires no additional cores, specialized hardware or changes to
existing software. Open source libraries, third party binaries and
legacy code can be configured in minutes to achieve unprecedented levels
of safety and security. /

**Comment by borancar** [comment]
Not using, but future-proofing/opening up the possibilty of using. Set arch riscv:rv32 is a no-op for the gdb hex-five provides, but should the compiler/gdb be upgraded, it may become a necessity. So far, the SiFive compiler/gdb allowed me to compile using the command-line on Windows.

**Comment by cgarlati** [comment]
Is riscv:rv32 1) gdb parameter 2) openocd parameter 3) SiFive's openocd
driver (fespi) parameter?

BTW, what is has to do with the gcc compiler?

Cesare Garlati | Hex Five Security, Inc. | www.hex-five.com | Ph 408 667
3320

/*Hex Five Security, Inc.* is the creator of MultiZone™ Security, the
first trusted execution environment for RISC-V. Hex Five patent pending
technology provides policy-based hardware-enforced separation for an
unlimited number of security domains, with full control over data, code
and peripherals. Contrary to traditional solutions, Hex Five MultiZone™
requires no additional cores, specialized hardware or changes to
existing software. Open source libraries, third party binaries and
legacy code can be configured in minutes to achieve unprecedented levels
of safety and security. /

**Comment by borancar** [comment]
It's a gdb command that needs to be executed during the gdb session, otherwise gdb can incorrectly assume the architecture when trying to upload or debug.

Both gcc and gdb are compiled and bundled together so a downloaded compiler/toolchain includes both.

**Comment by cgarlati** [comment]
Boran, Is this a new gdb requirement or another SiFive hack? Check the
official RISC-V gnu toolchain repo and see in what release if was
introduced - if ever.

BTW, gdb and gcc are not the same executable: what has riscv:rv32 to do
with gcc?

Cesare Garlati | Hex Five Security, Inc. | www.hex-five.com | Ph 408 667
3320

/*Hex Five Security, Inc.* is the creator of MultiZone™ Security, the
first trusted execution environment for RISC-V. Hex Five patent pending
technology provides policy-based hardware-enforced separation for an
unlimited number of security domains, with full control over data, code
and peripherals. Contrary to traditional solutions, Hex Five MultiZone™
requires no additional cores, specialized hardware or changes to
existing software. Open source libraries, third party binaries and
legacy code can be configured in minutes to achieve unprecedented levels
of safety and security. /

**Comment by borancar** [comment]
`set arch` is something that's gdb standard. What I believe has happened is that the default was switched from 32-bit to 64-bit in SiFive's latest compilers. The reason an issue would happen is that hex file doesn't include any architecture information.

Nothing to do with gcc, just the tar.gz file contains both of them.

**Comment by cgarlati** [comment]
@borancar Did you test the E51 / 64-bit? Set arch can't be fixed in the make file but should depend from the target board.

**Comment by cgarlati** [comment]
@borancar Once fixed, apply same change to multizone-sdk

**Pull request merged**
