### PR TITLE
Separate mzmsg and telnet

### PR DESCRIPTION
**Pull request by borancar**
Use a pair of queues to decouple the 2 processes.

### CODE REVIEW

**Comment by cgarlati** [comment]
Telnet editing is completely broken

**Comment by borancar** [comment]
@sandro2pinto, could you take this on for me? I could use some help here, but it could be also be part of your solution for https://github.com/hex-five/multizone-secure-iot-stack/issues/19

**Comment by sandro2pinto** [comment]
Sure @borancar

**Comment by borancar** [comment]
Fix to be delivered in https://github.com/hex-five/multizone-secure-iot-stack/pull/24.

**Pull request closed without merging**
