### PR TITLE
P1 bug fixes and TLS support

### PR DESCRIPTION
**Pull request by borancar**

### CODE REVIEW

**Comment by cgarlati** [comment]
Telnet editing completely broken

**Comment by borancar** [comment]
Thanks, that seems to be a result of the first commit, now extracted as #26, and to be handled separately.

**Comment by borancar** [comment]
> Telnet editing completely broken

Fixed now, was due to flushing not emptying the queue fully

**Comment by cgarlati** [comment]
TLS Session doesn't work:
stty -icanon -echo && openssl s_client -crlf -connect 192.168.0.2:443

prints 
"CONNECTED(00000003)"

then nothing happens

**Comment by borancar** [comment]
My wireshark captures indicates the need to wait at least 3.4 seconds before the server starts responding. Could you use the following patch and capture the interactions, please?
```
diff --git a/zone2/main.c b/zone2/main.c
index 5a2ee2b7..a25231f7 100644
--- a/zone2/main.c
+++ b/zone2/main.c
@@ -370,9 +370,12 @@ void tls_client(WOLFSSL *ssl, struct queue *txq, struct queue *rxq)
 
     ret = wolfSSL_accept(ssl);
     error = wolfSSL_get_error(ssl, 0);
+    ECALL_SEND(4, (int[4]){1, ret, error, 0});
 
     if (ret != WOLFSSL_SUCCESS) {
         ret = wolfSSL_accept(ssl);
+        error = wolfSSL_get_error(ssl, 0);
+        ECALL_SEND(4, (int[4]){1, ret, error, 0});
     } else {
         if (qfree(rxq) < MZMSG_CHARS || rxq->flush) {
             bytes = wolfSSL_write(ssl, qfront(rxq), qcontlen(rxq));
diff --git a/zone3/main.c b/zone3/main.c
index a626e3b5..a54edd8f 100644
--- a/zone3/main.c
+++ b/zone3/main.c
@@ -47,6 +47,8 @@ void eccSign(unsigned int inSz, unsigned int outSz)
     int msg[4];
     int i, ret;
 
+    ECALL_SEND(4, (int[4]){1, inSz, outSz, 0});
+
     in = (unsigned char*)malloc(inSz);
     out = (unsigned char*)malloc(outSz);
 
@@ -65,6 +67,7 @@ void eccSign(unsigned int inSz, unsigned int outSz)
     msg[1] = ret;
     msg[2] = outSz;
     msg[3] = 0;
+    ECALL_SEND(4, msg);
     ECALL_SEND(2, msg);
     ECALL_YIELD();
 
diff --git a/zone4/main.c b/zone4/main.c
index f1a199c4..8747cd5b 100644
--- a/zone4/main.c
+++ b/zone4/main.c
@@ -392,13 +392,14 @@ void print_pmp_ranges(void){
 		ECALL_RECV(2, msg);
 
 		if (msg[0]){
+            char buf[32];
 
 			write(1, "\e7", 2); // save curs pos
 			write(1, "\e[2K", 4); // 2K clear entire line - cur pos dosn't change
 
 			switch (msg[0]) {
 			case 'p' : write(1, "\rZ2 > pong\r\n", 12); break;
-			default  : write(1, "\rZ2 > ???\r\n", 11); break;
+			default  : write(1, buf, snprintf(buf, 32, "\rZ2 > %d %d %d %d\r\n", msg[0], msg[1], msg[2], msg[3])); break;
 			}
 
 			write(1, "\nZ4 > ", 6);
@@ -410,6 +411,7 @@ void print_pmp_ranges(void){
 		ECALL_RECV(3, msg);
 
 		if (msg[0]){
+            char buf[32];
 
 			write(1, "\e7", 2); // save curs pos
 			write(1, "\e[2K", 4); // 2K clear entire line - cur pos dosn't change
@@ -417,7 +419,7 @@ void print_pmp_ranges(void){
 			switch (msg[0]) {
 			case 331 : write(1, "\rZ3 > CLINT IRQ 23 [BTN3]\r\n", 27); break;
 			case 'p' : write(1, "\rZ3 > pong\r\n", 12); break;
-			default  : write(1, "\rZ3 > ???\r\n", 11); break;
+			default  : write(1, buf, snprintf(buf, 32, "\rZ2 > %d %d %d %d\r\n", msg[0], msg[1], msg[2], msg[3])); break;
 			}
 
 			write(1, "\nZ4 > ", 6);
```

**Comment by borancar** [comment]
Also, to eliminate any potential problems with your openssl not supporting TLS 1.3, try demanding TLS 1.3 with:
```
stty -icanon -echo && openssl s_client -tls1_3 -crlf -connect 192.168.0.2:443
```

**Comment by borancar** [comment]
That would mean your openssl client doesn't support TLS 1.3, sadly :(. Try:
```
openssl version
```

I'm using
```
% openssl version
OpenSSL 1.1.1a FIPS  20 Nov 2018
```

**Comment by cgarlati** [comment]
I am on Debian stable (stetch). 
openssl version is OpenSSL 1.1.0j  20 Nov 2018
It does not support TLS 1.3

 openssl s_client --help
...
-tls1                      Just use TLSv1
-tls1_1                    Just use TLSv1.1
-tls1_2                    Just use TLSv1.2
...

Any ideas?

**Comment by borancar** [comment]
One would be to either compile a newer version of openssl locally and use the s_client from there. Another would be to get a VM or a Docker container with a more recent openssl version. You could try another client like GnuTLS. We sadly don't support using a web browser as we don't support HTTPS.

**Pull request merged**
